"""create tables

Revision ID: 805c3dd7e33b
Revises: 
Create Date: 2024-10-24 12:32:49.003836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805c3dd7e33b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tag',
    sa.Column('tagnumber', sa.Integer(), nullable=False),
    sa.Column('outline', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tagnumber')
    )
    op.create_table('Todo',
    sa.Column('Todonumber', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('done_tasks', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Todonumber')
    )
    op.create_table('Settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Todonumber', sa.Integer(), nullable=True),
    sa.Column('tagnumber', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Todonumber'], ['Todo.Todonumber'], ),
    sa.ForeignKeyConstraint(['tagnumber'], ['Tag.tagnumber'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Settings')
    op.drop_table('Todo')
    op.drop_table('Tag')
    # ### end Alembic commands ###
