"""create tables

Revision ID: ff4bc0ce7aa9
Revises: 805c3dd7e33b
Create Date: 2024-10-24 17:12:00.025666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff4bc0ce7aa9'
down_revision: Union[str, None] = '805c3dd7e33b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outline', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('done_tasks', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Settings')
    op.drop_table('Todo')
    op.drop_table('Tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Todonumber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tagnumber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Todonumber'], ['Todo.Todonumber'], name='Settings_Todonumber_fkey'),
    sa.ForeignKeyConstraint(['tagnumber'], ['Tag.tagnumber'], name='Settings_tagnumber_fkey'),
    sa.PrimaryKeyConstraint('id', name='Settings_pkey')
    )
    op.create_table('Tag',
    sa.Column('tagnumber', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('outline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tagnumber', name='Tag_pkey')
    )
    op.create_table('Todo',
    sa.Column('Todonumber', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('done_tasks', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Todonumber', name='Todo_pkey')
    )
    op.drop_table('settings')
    op.drop_table('todo')
    op.drop_table('tag')
    # ### end Alembic commands ###
